### ISSUE TITLE
telegraf_install resource fails on Amazon Linux

### ISSUE THREAD

**Issue by jschnare** [NorthPage/telegraf-cookbook#15]
On Amazon Linux the platform_family? is reported as `rhel`, but `$releasever` looks like `2015.09.1`.  The repo contains only CentOS releases 5, 6, and 7.  I've been setting up the yum repo manually to use rhel/7 so the `baseurl` looks like:

```
https://repos.influxdata.com/rhel/7/\$basearch/stable
```

This works fine for me.  Perhaps `baseurl` should be exposed as an attribute?

**Comment by tenyo** [comment]
I think I'd rather make sure it installs properly on Amazon Linux out of the box. Adding a baseurl seems a little yucky as it only applies to yum repositories and then you may also need to override the key and other parameters.
In the meantime, we just released a new version based on #12 which may help as you'll be able to define your repository separately and not rely on the one used by the telegraf_install resource.

**Comment by jschnare** [comment]
That's a reasonable solution, thank you.

**Comment by fishnix** [comment]
This is fixed in https://github.com/NorthPage/telegraf-cookbook/pull/16
