### ISSUE TITLE
telegraf_plugins config files should not be world readable

### ISSUE THREAD

**Issue by jwmarshall** [NorthPage/telegraf-cookbook#18]
Since telegraf plugin configurations often require passwords and secret information they should not be world readable. I will try to provide a simple PR tomorrow.

https://github.com/NorthPage/telegraf-cookbook/blob/master/resources/plugins.rb#L46

**Comment by fishnix** [comment]
This is fixed by https://github.com/NorthPage/telegraf-cookbook/pull/19

**Comment by jwmarshall** [comment]
A+ thank you
