### ISSUE TITLE
Latest release is causing invalid <name>_output.conf files to be created

### ISSUE THREAD

**Issue by Dan-Kitchen** [NorthPage/telegraf-cookbook#24]
Hi guys,

As the title says the latest cookbook version is creating invalid config files. If you look at the below:

`[[outputs]]
[outputs.influxdb]
database = "telegraf"
......`

The [[outputs]] line is invalid and is not present in the accompanying <name>_inputs.conf:

`[inputs.cpu]
drop = ["cpu_time"]
percpu = true
totalcpu = true
[inputs.mem]
[inputs.net]
[inputs.netstat]
[inputs.processes]
[inputs.procstat]
.......`

I'm not convinced it is the cookbook code as this has not changed in the last few days. Furthermore the usage is standard as per you README. We only pinned the minimum & not maximum version of your cookbook.

Whilst I haven't delved too much into the why it would seem it is something to do with the TOML gem you are now using.

Thanks :)

**Comment by fishnix** [comment]
@Dan-Kitchen What version are you using?  If you are running off of master, its possible to have this issue until we merge up the open PRs.  If you're using `0.3.4`, you might see this issue if you installed the toml-rb gem after they released `0.3.13` which was breaking.  If you are using `0.3.5` (which is the latest as of yesterday), I think you should be okay.

**Comment by Dan-Kitchen** [comment]
@fishnix Yeah that makes a lot of sense. We were using 0.3.4. A bunch of servers we spun up in the last day obviously pulled in this gem. It would appear though that using the new cookbook doesn't fix the issue if it's already happened. Until you remove the toml-rb 0.3.13 gem it will still generate invalid config files. It might be worth putting out a bit of info somewhere about that.

Thanks for the response!

**Comment by fishnix** [comment]
Yeah that's true, we will install and upgrade that gem but not downgrade it.  Sorry for the trouble, unfortunately the upstream gem released a breaking change on a patch release and we weren't pinning the version. :hushed: With the next version (0.4.0), we will pin to 0.3.x and fix the output.  :+1:

**Comment by Dan-Kitchen** [comment]
Thankfully it only affected two of our nodes :)

No worries buddy, these things happen :+1:
