### ISSUE TITLE
Conflict with influxdb cookbook

### ISSUE THREAD

**Issue by cyberflow** [NorthPage/telegraf-cookbook#26]
Both cookbooks add `https://repos.influxdata.com/ubuntu` repository but with different options (influxdb use only stable branch, telegraf use stable and unstable). If use both cookbook it's rewriting apt source list every run.

**Comment by tenyo** [comment]
I think we initially did this so you could install the previous version of telegraf from the unstable repo, but that's probably not that helpful and better to be consistent with the influxdb cookbook. I've opened #27 to fix this.
