### ISSUE TITLE
Multiple Service processes

### ISSUE THREAD

**Issue by Dan-Kitchen** [NorthPage/telegraf-cookbook#32]
Hi all,

Having an issue whereby multiple processes are spawned from the service definitions created by the cookbook. It seems to be new behaviour although, confusingly your version hasn't changed since we started using Telegraf. Some more info:

**service definition:**

```
[Unit]
Description=The plugin-driven server agent for reporting metrics into InfluxDB
Documentation=https://github.com/influxdata/telegraf
After=network.target

[Service]
EnvironmentFile=-/etc/default/telegraf
User=micro
ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d ${TELEGRAF_OPTS}
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
KillMode=process

[Install]
WantedBy=multi-user.target
Alias=telegraf.service
```

**systemctl output**:

```
telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/usr/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-06-30 14:41:02 UTC; 1 weeks 3 days ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 16983 (telegraf)
   CGroup: /system.slice/telegraf.service
           ├─15459 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
           └─16983 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
```

**ps output**:

```
dkitchen  2268  0.0  0.0 112648   968 pts/0    S+   13:05   0:00 grep --color=auto telegraf
telegraf 15459  0.1  0.3 410960 27128 ?        Sl   Jun30  27:37 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
micro    16983  1.9  0.3 475952 23876 ?        Ssl  Jun30 300:00 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
```

In some cases this is harmless but in some cases it seems to first spawn a 'zombie' process. When the second one comes up it cannot bind the port and we get no metrics. You guys have any ideas what could cause this?

**Comment by Dan-Kitchen** [comment]
Upon further investigation it seems like an error in how we are using the cookbook. It seems we are accidentally spawning a second process by messing around with the service def. Will find out for sure and will close if unneeded.

**Comment by fishnix** [comment]
Thanks @Dan-Kitchen - let us know!

**Comment by Dan-Kitchen** [comment]
Hi guys,

Apologies it seems it is not an issue with you guys, but the latest Telegraf version 0.13.1. It seems this version was released with a bug which causes multiple zombie processes when telegraf spins up. There was a fix a day after 0.13.1 but there is yet to be another release, see: https://github.com/influxdata/telegraf/pull/1252

We were not pinning our Telegraf version. This has been changed now and pinned to 0.13.0 until a new release. However one issue is that the cookbook will not downgrade or install a version if a later version is installed. Is this functionality you wish to add or would mind me adding in a PR? Specifically the ability to flag an install to downgrade if needed or just install the required version regardless of if a later version is previously installed?

**Comment by fishnix** [comment]
Thanks for the update @Dan-Kitchen!  I would review a PR for installing a downgraded version as long as it could be done cleanly.  I don't think there should be any special flag though, the version should take care of it.  

Ultimately, pinning is the right answer, I think.  We did have a default version for a while but that caused folks some other issues.  It might make sense to include that in our README.

**Comment by fishnix** [comment]
Closing this issue.  Thanks!
