### ISSUE TITLE
Missing yum resource repository in new yum version 5.0

### ISSUE THREAD

**Issue by barrebre** [NorthPage/telegraf-cookbook#36]
Hello all,

I was failing my kitchen converge with this output:
       Converging 3 resources
       Recipe: build-essential::default
         * build_essential[install_packages] action install
           * yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch] action install
             - install version 2.5.37-3.el7 of package flex
         
       Recipe: telegraf::default
         * telegraf_install[default] action create
           
           ================================================================================
           Error executing action `create` on resource 'telegraf_install[default]'
           ================================================================================
           
           NoMethodError
           -------------
           No resource or method named `yum_repository' for `Custom resource telegraf_install from cookbook telegraf action provider "default"'
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/telegraf/resources/install.rb:31:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/telegraf/recipes/default.rb
           
            19: telegraf_install 'default' do
            20:   include_repository node['telegraf']['include_repository']
            21:   install_version node['telegraf']['version']
            22:   action :create
            23: end
            24: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/telegraf/recipes/default.rb:19:in `from_file'
           
           telegraf_install("default") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :telegraf_install
             cookbook_name "telegraf"
             recipe_name "default"
             include_repository true
             install_type "package"
           end

After digging, I found that the repository resource has been removed from yum 5.0 in their February update from yum 4.2. Has anyone else faced this issue? I was able to resolve by adding `depends 'yum', '= 4.2'` in my cookbook.

**Comment by fishnix** [comment]
Just curious -- what chef-client version?  They added support for yum_repository in 12.12 or 12.13 I think.  I'm unsure if that would take precedence or not...

**Comment by fishnix** [comment]
Closing this since I didn't hear back
