### ISSUE TITLE
Missing Inputs

### ISSUE THREAD

**Issue by skares** [NorthPage/telegraf-cookbook#45]
Hi, we tested the latest Version. Our Attribute File for Inputs look like this

node.default['telegraf']['inputs'] =  { 'cpu' => {'percpu' => true,'totalcpu' => true,'drop' => ['cpu_time']},  'disk' => {},  'io' => {},  'mem' => {},  'net' => {},  'swap' => {} }

Only CPU Input is creted in the default_inputs.conf

[inputs.cpu]
drop = ["cpu_time"]
percpu = true
totalcpu = true

when my attribute file is defined like that 
node.default['telegraf']['inputs'] =  { 'cpu' => {'percpu' => true,'totalcpu' => true,'drop' => ['cpu_time']}, 'disk' => {  'mount_points' => ['/']}  }

Then the default_inputs.conf looks like this

[inputs.cpu]
drop = ["cpu_time"]
percpu = true
totalcpu = true

[inputs.disk]
mount_points = ["/"]

So all { } entries will not be created . Please help.

Cheers Sven

**Comment by slillibri** [comment]
I saw the same. It looks like the toml rubygem doesn't output the empty hash values. I am getting around this by setting the value to a comment, i.e.
```ruby
node.default['telegraf']['inputs'] = {'mem' => {'#null' => ''}}
```
This should produce something like the following
```toml
[inputs.mem]
#null = ""
```

**Comment by skares** [comment]
Thanks for providing the workaround. Hope for a better solution in the next release.

**Comment by fishnix** [comment]
Hi @skares - thanks for the report, I believe this will be fixed in the next release (due shortly).  Please reopen if you continue to have problems.  Thanks!

**Comment by romerojunior** [comment]
@slillibri thanks for the workaround!
