### ISSUE TITLE
Telegraf 0.10 renames plugins -> inputs

### ISSUE THREAD

**Issue by donaldguy** [NorthPage/telegraf-cookbook#5]
Are you going to follow suit?

**Comment by fishnix** [comment]
Hi!  Thanks for reaching out.  It looks like telgraf 0.10 is not backwards compatible with older versions (including the database format...), so we'll have to figure this out.  So far we haven't tested v0.10 at all.  Are you using v0.10?

**Comment by donaldguy** [comment]
Our TICK stack isn't in real operation yet, so I kinda feel like we might as well roll forward

(also probably more like TIGK where the G is grafana)

**Comment by tenyo** [comment]
Looks like quite a few changes, from plugins/inputs to the config file and binary location. I think we can modify the cookbook to support both 0.10 and earlier. 
The package repos haven't been updated yet with 0.10 but when they do the cookbook (in its current state) will break as it's installing the latest version but the configuration is for pre-0.10.

**Comment by fishnix** [comment]
I opened https://github.com/NorthPage/telegraf-cookbook/issues/7
