### ISSUE TITLE
NP-2492 Support telegraf 0.10.x

### ISSUE THREAD

**Issue by fishnix** [NorthPage/telegraf-cookbook#7]
telegraf 0.10.x has brought some breaking changes.  We need to update the cookbook to support those changes.  _Note:_ the database format also changed, but migrating databases should be out of scope.

**Comment by tenyo** [comment]
@fishnix should the new version of the cookbook try to support both 0.10 and 0.2.x, or do we decide it only works with 0.10 and the new syntax?
